Repository Shopify/vscode-ruby-lsp, pull requests merged in 2023-11, with the labels that each got.

#867 Show an error if VS Code doesn't have permission to write on the working folder
  src/client.ts
Labels: bugfix

#870 Add ovsx package
  package.json
  yarn.lock
Labels: chore

#868 Avoid printing to stdout from Client or Ruby activation
  src/client.ts
  src/ruby.ts
Labels: bugfix

#885 Escape spaces in shell path
  src/ruby.ts
Labels: bugfix

#904 Remove newlines from Ruby activation script
  src/ruby.ts
Labels: bugfix

#897 Fix in/when dedent with language configuration
  languages/ruby.json
  package.json
Labels: bugfix

#907 Read server information from initialize result
  src/client.ts
  src/status.ts
  src/test/suite/status.test.ts
Labels: bugfix

#913 Fix weird indentation for on-type completion
  src/client.ts
Labels: bugfix

#914 Build test items in hierarchy if it's supported
  src/testController.ts
Labels: enhancement

#917 Apply the `branch` flag to debug mode too
  src/client.ts
Labels: bugfix
