Repository Shopify/vscode-ruby-lsp, pull requests merged in 2023-08, with the labels that each got.

#722 Add client start test
  src/client.ts
  src/test/suite/client.test.ts
Labels: chore

#712 Make extension work on Windows
  src/client.ts
  src/ruby.ts
Labels: bugfix, os:windows

#735 Add early return when shadowenv returns an empty string
  src/ruby.ts
Labels: bugfix

#744 Run the server with bundle exec for user defined custom bundle
  src/client.ts
Labels: bugfix

#748 Time out tests that don't finish under 30 seconds
  package.json
  src/testController.ts
Labels: bugfix

#765 Add workspace symbol configuration
  package.json
Labels: enhancement

#771 Show server version in status language item
  src/client.ts
  src/status.ts
  src/test/suite/status.test.ts
Labels: enhancement
