Repository Shopify/vscode-ruby-lsp, pull requests merged in 2023-03, with the labels that each got.

#336 Add "none" as option for Ruby Version Manager
  package.json
  src/ruby.ts
Labels: bugfix

#429 Avoid mutating the environment with RUBYOPT
  package.json
  src/client.ts
Labels: bugfix

#422 Allow selecting version manager next to Ruby version
  package.json
  src/client.ts
  src/ruby.ts
  src/status.ts
Labels: enhancement

#437 Introduce `auto` option for version manager
  README.md
  package.json
  src/ruby.ts
Labels: enhancement

#445 Allow marking features as experimental
  src/client.ts
Labels: bugfix

#455 Use absolute path to for eval_gemfile
  src/client.ts
Labels: bugfix

#456 Pass `env` to ruby invocation
  src/ruby.ts
  src/test/suite/ruby.test.ts
Labels: bugfix

#459 Fail gracefully on ruby activation errors
  src/client.ts
  src/extension.ts
  src/ruby.ts
  src/status.ts
Labels: bugfix

#475 Contribute config defaults to exclude .ruby-lsp from search and file tree
  package.json
Labels: enhancement

#477 Upgrade to TypeScript 5.0.2
  package.json
  yarn.lock
Labels: dependencies

#490 Update server status when the server is running
  src/status.ts
  src/test/suite/status.test.ts
Labels: bugfix

#499 Remove bundle migration message
  src/client.ts
Labels: bugfix

#511 Do not attempt to run server on old rubies
  src/ruby.ts
Labels: bugfix

#515 Abort existing bundle install if another restart is triggered
  src/client.ts
Labels: bugfix
