Repository Shopify/vscode-ruby-lsp, pull requests merged in 2023-09, with the labels that each got.

#786 Allow configuring when to pull diagnostics
  package.json
  src/client.ts
Labels: enhancement

#800 Group minor and patch upgrades
  .github/dependabot.yml
Labels: chore

#701 Mention a fallback for `chruby` users if project doesn't have `.ruby-version`
  README.md
  VERSION_MANAGERS.md
Labels: documentation

#808 Add references configuration
  package.json
Labels: enhancement
